config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
  match "/attending"=>"home#mark_stat", via: [:get], :as=>"mark_stat"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wed_attender.rb
class WedAttender < ApplicationRecord

  def status_name
    if status == 1
      return "Attending"
    elsif status == 2
      return "Maybe"
    elsif status == 3
      return "Not Attending"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    respond_to do |format|
      format.html
    end
  end

  def attenders
    respond_to do |format|
      format.html
    end
  end

  def mark_stat

    cookie_id = cookies[:visitor_cookie] || DateTime.now.strftime('%Q')
    cookies[:visitor_cookie] = { value: cookie_id, expires: 1.year.from_now }
    wd = WedAttender.where("cookie_id=?",cookie_id).take
    if wd.blank?
      wd = WedAttender.new
    end
    wd.att_name = params[:name]
    wd.status = params[:stat]
    wd.cookie_id = cookie_id
    wd.save

    cookies[:att_status] = { value: wd.status, expires: 1.year.from_now }

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_about.html.erb
<!-- content -->
<div class="page-content clearfix">
  <div class="row">
    <div class="col-xs-12">
      <!-- Section: About Us -->
      <div class="section-about-us">
        <!-- Title 1 -->
        <h1 class="title1 couple-title1 title1-border">About Us</h1>
        <!-- /Title 1 -->
        <div class="row">
          <!-- Groom -->
          <div class="col-sm-6">
            <div class="about-item">
              <div class="about-item-picture">
                <%=image_tag "groom.jpg"%>
              </div>
              <h2 class="about-item-title">Manju Prasad (Linith)</h2>
              <h3 class="about-item-subtitle">The Groom</h3>
              <div class="about-item-content">
                <p>Deshi is kind, loving and thoughtful. I fell for her dimple smile ;) I love the way she brings joy each time I am with her. She is definitely a best gift for me in life...</p>
              </div>
            </div>
          </div>
          <!-- /Groom -->

          <!-- Bride -->
          <div class="col-sm-6">
            <div class="about-item">
              <div class="about-item-picture">
                <%=image_tag "bride.jpg"%>
              </div>
              <h2 class="about-item-title">Deshitha</h2>
              <h3 class="about-item-subtitle">The Bride</h3>
              <div class="about-item-content">
                <p>Time of waiting for my soul mate finally ended when I met Linu for the first time... Eagerly waiting to tell the whole world that he will be mine forever. I'm sure I will spend rest of my life to be the best partner and the best friend for him and I will be here for you in good times and in bad until death do us part... </p>
              </div>
            </div>
          </div>
          <!-- /Bride -->
        </div>
      </div>

      <!-- /Section: About Us -->
      <!-- Section: Timeline -->
      <div class="section-timeline">
        <!-- Title 1 -->
        <h2 class="title1 couple-title1 title1-border">Our Timeline</h2>
        <!-- /Title 1 -->
        <!-- timeline -->
        <ul class="timeline">
          <!-- item -->
            <li>
              <!-- badge -->
              <div class="timeline-badge">
                <span class="timeline-date">20/04</span>
                <span class="timeline-year">2019</span>
              </div>
              <!-- /badge -->
              <!-- panel -->
                <div class="timeline-panel">
                  <!-- item heading -->
                  <div class="timeline-heading">
                      <h4 class="timeline-title">Day we meet each other</h4>
                      <p><small class="text-muted">A special day for us!</small></p>
                  </div>
                  <!-- /item heading -->
                  <!-- item body -->
                  <div class="timeline-body">
                      <p>We have met each other in April 20 2019, the best day in our life.!</p>
                  </div>
                  <!-- /item body -->
                </div>
                <!-- /panel -->
            </li>
            <!-- /item -->
            <!-- item -->
            <li class="timeline-inverted">
              <!-- badge -->
              <div class="timeline-badge bg-color1">
                <span class="timeline-date">25/04</span>
                <span class="timeline-year">2019</span>
              </div>
              <!-- /badge -->
              <!-- panel -->
                <div class="timeline-panel">
                  <!-- item heading -->
                  <div class="timeline-heading">
                      <h4 class="timeline-title">Day we agreed!</h4>
                  </div>
                  <!-- /item heading -->
                  <!-- item body -->
                  <div class="timeline-body">
                      <p>We agreed foreever on this beautiful day.</p>
                  </div>
                  <!-- /item body -->
                </div>
                <!-- /panel -->
            </li>
            <!-- /item -->
            <!-- item -->
            <li>
              <!-- badge -->
              <div class="timeline-badge">
                <span class="timeline-date">19/10</span>
                <span class="timeline-year">2019</span>
              </div>
              <!-- /badge -->
              <!-- panel -->
                <div class="timeline-panel">
                  <!-- item heading -->
                  <div class="timeline-heading">
                      <h4 class="timeline-title">Our Engagement</h4>
                    <p><small class="text-muted">A joyful day. And its Linth's Birthday.!!!!</small></p>
                  </div>
                  <!-- /item heading -->
                  <!-- item body -->
                  <div class="timeline-body">
                    <%=image_tag "ring2.png"%>
                  </div>
                  <!-- /item body -->
                </div>
                <!-- /panel -->
            </li>
            <!-- /item -->
            <!-- item -->
            <li class="timeline-inverted">
              <!-- badge -->
              <div class="timeline-badge bg-color1">
                <span class="timeline-date">03/11</span>
                <span class="timeline-year">2019</span>
              </div>
              <!-- /badge -->
              <!-- panel -->
                <div class="timeline-panel">
                  <!-- item heading -->
                  <div class="timeline-heading">
                      <h4 class="timeline-title">Our Wedding Day</h4>
                  </div>
                  <!-- /item heading -->
                  <!-- item body -->
                  <div class="timeline-body">
                      <p>It will be a big day! Our family, friends celebrating with their families the day with dinner and a champagne toast.</p>
                  </div>
                  <!-- /item body -->
                </div>
                <!-- /panel -->
            </li>
            <!-- /item -->
        </ul>
        <!-- /timeline -->
      </div>
      <!-- /Section: Timeline -->
    </div>
  </div>
</div>
<!-- /content -->

app/views/home/_ceramony.html.erb
<!-- content -->
  <div class="page-content">
    <div class="row">
      <div class="col-xs-12">
        <!-- mai title -->
        <h2 class="title1 couple-title1 title1-border">Ceremony</h2>
        <!-- /main title -->
        <div class="page-intro">
          <p>Joining on our wedding ceramony? Well here’s the details on the big day!<br/> See you there!</p>
        </div>
        <div class="row row-maps">
          <!-- Map -->
          <div class="col-sm-6">
            <div class="ceremony-item">
            <h2 class="title3">Main Ceremony</h2>
            <p>We like everything on the wedding day be perfect!</p>
            <h3 class="title4" style="margin-left: -10px;margin-right: -10px;">Kurunji Janaki Venkataramana Gowda Sabha Bhavana</h3>
            <p>Sullia, Dakshina Kannada</p>

            <h3 class="title4" style="font-size:18px;">03 Nov 2019 <br> 10:50 AM onwards</h3>
            <!-- iframe -->
            <div class="iframe-wrapper">
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d42528.80032787671!2d75.4175883876708!3d12.543755379873653!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x2183d1361d09098c!2sK.V.G%20Samudaya%20Bhavan!5e0!3m2!1sen!2sin!4v1567789163746!5m2!1sen!2sin" height="220"  style="border:0"></iframe>
            </div>
            <!-- /iframe -->
            </div>
          </div>
          <!-- /Map -->
          <!-- Map -->
          <div class="col-sm-6">
            <div class="ceremony-item">
              <h2 class="title3">Wedding Party / Mehandi</h2>
              <p>A cocktail party. Beer on us!</p>
              <h3 class="title4">Kurunji House, Aranthodu</h3>
              <p>Sullia D.K</p>
              <!-- iframe -->
              <h3 class="title4" style="font-size:18px;">01 Nov 2019 <br> 06:00 PM onwards</h3>
              <div class="iframe-wrapper">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3836.0910522942418!2d75.46616955822567!3d12.51849877153823!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba4f111d28f756f%3A0x5f816f17d873748!2sAranthodu!5e0!3m2!1sen!2sin!4v1567790322043!5m2!1sen!2sin" height="220"  style="border:0"></iframe>
              </div>
              <!-- /iframe -->
            </div>
          </div>
          <!-- /Map -->
        </div>
      </div>
    </div>
  </div>
  <!-- /content -->

app/views/home/_gallery.html.erb
<div class="row">
  <div class="col-xs-12 couple-container">
    <!-- Title 1 -->
    <h1 class="title1 couple-title1 title1-border">Our Pictures</h1>
    <!-- /Title 1 -->
    <!-- Gallery -->
    <div class="row-fluid pic_gallery">
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('cake.jpg')%>" alt="">
            <div class="picture-legend">Thank you!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('ring.png')%>" alt="">
            <div class="picture-legend">Our rings!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="<%=asset_path('i1.jpg')%>" >
            <img src="<%=asset_path('i1.jpg')%>" alt="">
            <div class="picture-legend">Home! Sweet Home..</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('manju2.png')%>" alt="">
            <div class="picture-legend">Blessed!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item <-->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('p3.jpg')%>" alt="">
            <div class="picture-legend">Family Time!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->

      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('manju.jpg')%>" alt="">
            <div class="picture-legend">Together forever!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->

      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('p2.jpg')%>" alt="">
            <div class="picture-legend">Family Time!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('p5.jpg')%>" alt="">
            <div class="picture-legend">Fun Time!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="<%=asset_path('p7.jpg')%>" >
            <img src="<%=asset_path('p7.jpg')%>" alt="">
            <div class="picture-legend">The Gang..!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('i2.jpg')%>" alt="">
            <div class="picture-legend">Sweet!!!!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('i3.jpg')%>" alt="">
            <div class="picture-legend">Joining Hands Soon..!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('i4.jpg')%>" alt="">
            <div class="picture-legend">Sweet Home..</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('i5.jpg')%>" alt="">
            <div class="picture-legend">Blessed!</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
      <!-- item -->
      <div class="col-sm-3">
        <div class="cont">
          <a href="javascript:void(0);" >
            <img src="<%=asset_path('i6.jpg')%>" alt="">
            <div class="picture-legend">Gang of Girls..</div>
            <div class="mask"></div>
          </a>
        </div>
      </div>
      <!-- /item -->
    </div>
    <!-- /Gallery -->
  </div>
</div>

<style type="text/css">
  .pic_gallery img{
    width: 100%;
  }

  .pic_gallery .cont{
    background: #fff;
    padding:10px;
    overflow: auto;
  }

  .pic_gallery .col-sm-3{
    margin-top: 15px;
  }
  .pic_gallery .picture-legend{
    color:#000;
  }

  .ceremony-item{
    border: 1px dashed #fff;
    margin-bottom: 15px;
  }

  .about-item{
    border: 1px dashed #fff;
    margin-bottom: 15px;
  }
</style>

app/views/home/attenders.html.erb
<div id="body" class="viewport animated">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>S.No</th>
        <th>Name</th>
        <th>Status</th>
        <th>Marked On</th>
      </tr>
    </thead>
    <tbody>
      <%WedAttender.order("created_at desc").each_with_index do |att,index|%>
        <tr>
          <td><%=(index+1)%></td>
          <td><%=att.att_name%></td>
          <td><%=att.status_name%></td>
          <td><%=att.created_at%></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/home/index.html.erb
<!-- Main Content
================================================== -->
<div id="body" class="viewport animated">
  <div class="container">
    <div class="boxed-content">
      <!-- Header -->
      <header id="header" class="navbar navbar-default navbar-static-top" >
        <div class="clearfix">
            <!-- logo -->
            <div class="hd-logo">
              <a href="index.html">
                <%=image_tag "logo_small.png"%>
              </a>
            </div>
            <!-- /logo -->
            <!-- responsive menu -->
            <!-- /responsive menu -->
            <!-- menu -->
            <div class="pause_cont">
              <%=image_tag "speaker.png",:style=>"width:60px;",:class=>"speaker",:spk=>"#{asset_path('speaker.png')}",:mute=>"#{asset_path('speaker_mute.png')}"%>
            </div>
            <!-- /menu -->
        </div>
      </header>
      <!-- /header -->
      <!-- content -->
      <div class="page-content page-home">
        <!-- home logo -->
        <div class="row">
          <div class="home-logo col-sm-8 col-sm-offset-2">
            <p class="couple-title" style="font-size:50px;">Manju & Deshi</p>
          </div>
        </div>
        <!-- /home-logo -->
        <!-- Countdown container -->
        <div class="row">
          <div class="countdown-container">
            <!-- icon -->
            <div class="countdown-icon">
              <%=image_tag "ico-heart2.png"%>
            </div>
            <!-- /icon -->
            <!-- countdown title top -->
            <h2 class="countdown-title countdown-title1"><span class="countdown-title-borders">November 03, 2019 <br> Kurunji Janaki Venkataramana Sabha Bhavana, Sullia</span></h2>
            <!-- /countdown title top -->
            <!-- countdown ( Edit it on main.js )-->
            <div class="row">
              <div class="col-xs-10 col-xs-offset-1">
                <div id="countdown" class="row"></div>
              </div>
            </div>
            <!-- /countdown -->
            <!-- countdown title bot -->
            <h3 class="countdown-title countdown-title2"><span class="countdown-title-borders">Until we get Married!</span></h3>
            <!-- countdown title /bot -->
          </div>
        </div>
        <!-- /Countdown Container -->
      </div>
      <!-- /content -->

      <div class="clearfix" style="border:1px dashed #fff; margin: 0px 3px; padding: 10px 5px;">
        <div class="row">
          <div class="col-xs-12">
            <!-- Section: About Us -->
            <div class="section-about-us">
              <!-- Title 1 -->
              <h1 class="title1 couple-title1">Attending?</h1>
              <%
                m1cls = "btn-default"
                m2cls = "btn-default"
                m3cls = "btn-default"
                if cookies[:att_status] == "1"
                  m1cls = "btn-success"
                elsif cookies[:att_status] == "2"
                  m2cls = "btn-success"
                elsif cookies[:att_status] == "3"
                  m2cls = "btn-success"
                end
              %>
              <div style="padding:10px 2px; text-align:center">
                <%=link_to mark_stat_path(:stat=>1),:class=>"btn #{m1cls} btn_att btn_1",:remote=>true do %>
                  <%=image_tag 'love.png',:style=>"margin-right:5px; height:18px;", :remote=>true%> YES
                <%end%>
                <%=link_to mark_stat_path(:stat=>2),:class=>"btn #{m2cls} btn_att btn_2", :remote=>true do %>
                  <%=image_tag 'confused.png',:style=>"margin-right:5px; height:18px;"%> MAYBE
                <%end%>
                <%=link_to mark_stat_path(:stat=>3),:class=>"btn #{m3cls} btn_att btn_3",:remote=>true do %>
                  <%=image_tag 'sad.png',:style=>"margin-right:5px; height:18px;"%> NO
                <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>


      <%=render "home/about"%>

      <%=render "home/ceramony"%>

      <%=render "home/gallery"%>

      <div style="background:#5c453f; color:#d6d4d4; font-size: 17px; padding:10px; font-weight:bold; text-align:center; margin-bottom:40px; margin-top:30px;">
        For more details contact:<br> 9113901948, 7026097300
      </div>

      <!-- footer -->
      <footer id="footer">
        <p class="footer-icon">
          <%=image_tag "ft-icon.png"%></p>
          <p class="quote-content">"When i saw you i fell in love, and you smiled because you knew."</p>
          <p class="quote-author">Willian Shakespeare</p>
          <audio loop class='player' volume="0.5">
            <source src="<%= asset_path 'valaga.mp3'%>">
          </audio>
      </footer>

      <div style="text-align:right; font-size:8px; color:#fff;">
        <span style="margin-right:3px;">Y-<%=WedAttender.where("status=1").count%></span>
        <span style="margin-right:3px;">M-<%=WedAttender.where("status=2").count%></span>
        <span style="margin-right:3px;">N-<%=WedAttender.where("status=3").count%></span>
      </div>

      <div style="background:#5c453f; color:#d6d4d4; font-size: 17px; padding:10px; font-weight:normal; text-align:center;">
        Created by - <a href="https:://www.kdkgowdas.com" target="_blank" style="color:#fff; text-decoration:underline;">www.kdkgowdas.com</a>
        <div style="font-size:13px; font-weight:normal;">
          For e-cards whatsapp @ <i class='fa fa-whatsapp'></i> 8088399377
        </div>

      </div>
      <!-- /footer -->
    </div>
  </div>
</div>
<!-- /Main Content
================================================== -->

<style type="text/css">
  .btn_att{
    padding: 5px 10px;
    margin: 0px 3px;
    font-weight: bold;
    border-radius: 2px;
  }
</style>

app/views/home/mark_stat.js.erb
$(".btn_1").addClass("btn-default").removeClass("btn-success");
$(".btn_2").addClass("btn-default").removeClass("btn-success");
$(".btn_3").addClass("btn-default").removeClass("btn-success");
$(".btn_<%=params[:stat]%>").removeClass("btn-default").addClass("btn-success");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wedding</title>
    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <title>Manju Weds Deshi</title>
    <link rel="apple-touch-icon" sizes="180x180" href="<%=asset_path('apple-touch-icon.png')%>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%=asset_path('favicon-32x32.png')%>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%=asset_path('favicon-16x16.png')%>">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <meta property="og:image" itemprop="image" content="http://www.manjuwedsdeshi.com<%=asset_path 'logo_small_og.png'%>">
    <meta property="og:type" content="website" />
    <link href='//fonts.googleapis.com/css?family=Great+Vibes' rel='stylesheet' type='text/css'>
		<link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tag %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-148518570-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-148518570-1');
    </script>

  </head>

  <body>
    <!-- Page Loader
    ========================================================= -->
    <div class="loader" id="page-loader">
      <div class="loading-wrapper">
        <div class="loader-heart loader-heart1"><%=image_tag "intro-heart.png" %></div>
        <div class="loader-heart loader-heart2"><%=image_tag "intro-heart.png" %></div>
        <div class="loader-heart loader-heart3"><%=image_tag "intro-heart.png" %></div>
      </div>
      <div class="play_container">
        <i class='fa fa-play'></i>
        <div class="play_text">OPEN</div>
      </div>
    </div>
    <!-- /End of Page loader
    ========================================================= -->

    <!-- === PAGE BACKGROUND === -->
    <!-- Background container -->
    <div class="page-background-container viewport">
      <!-- background-mask -->
      <div class="bg-mask viewport"></div>
      <!-- /background-mask -->
      <!-- background-slideshow -->
      <div class="bg-slideshow">
        <!-- slideshow-item -->
        <div class="page-background viewport" style="background-image: url('<%= asset_path 'slide.jpg'%>')"></div>
        <!-- /slideshow-item -->
      </div>
      <!--/Background-slideshow -->
    </div>
    <!-- Background-container -->
    <!-- === /PAGE BACKGROUND === -->

    <%= yield %>
  </body>
</html>